# Generated by Django 3.0.7 on 2020-06-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=300)),
                ('sekolah', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('periode', models.CharField(max_length=30)),
                ('surat', models.FileField(upload_to='surat/')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webkarirApp.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('keahlian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webkarirApp.Keahlian')),
            ],
        ),
        migrations.CreateModel(
            name='Lamaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto/')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=200)),
                ('transkrip', models.FileField(upload_to='transkrip/')),
                ('ijazah', models.FileField(upload_to='ijazah/')),
                ('cv', models.FileField(upload_to='cv/')),
                ('lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webkarirApp.Lowongan')),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webkarirApp.Profil')),
            ],
        ),
    ]
