# Generated by Django 3.0.7 on 2020-07-18 00:24

from django.db import migrations, models
import webkarirApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webkarirApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamaran',
            name='cv',
            field=models.FileField(upload_to='cv/', validators=[webkarirApp.validators.max_pdf_size]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='foto',
            field=models.ImageField(upload_to='foto/', validators=[webkarirApp.validators.max_photo_size]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='ijazah',
            field=models.FileField(upload_to='ijazah/', validators=[webkarirApp.validators.max_pdf_size]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='transkrip',
            field=models.FileField(upload_to='transkrip/', validators=[webkarirApp.validators.max_pdf_size]),
        ),
        migrations.AlterField(
            model_name='magang',
            name='surat',
            field=models.FileField(upload_to='surat/', validators=[webkarirApp.validators.max_pdf_size]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='no_hp',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
