# Generated by Django 3.0.7 on 2020-07-18 07:23

from django.db import migrations, models
import webkarirApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webkarirApp', '0002_auto_20200718_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamaran',
            name='cv',
            field=models.FileField(upload_to='cv/', validators=[webkarirApp.validators.max_pdf_size, webkarirApp.validators.pdf_valid]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='email',
            field=models.CharField(max_length=100, validators=[webkarirApp.validators.email_valid]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='foto',
            field=models.ImageField(upload_to='foto/', validators=[webkarirApp.validators.max_photo_size, webkarirApp.validators.jpeg_valid]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='ijazah',
            field=models.FileField(upload_to='ijazah/', validators=[webkarirApp.validators.max_pdf_size, webkarirApp.validators.pdf_valid]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='no_hp',
            field=models.CharField(max_length=15, validators=[webkarirApp.validators.hp_numeric]),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='transkrip',
            field=models.FileField(upload_to='transkrip/', validators=[webkarirApp.validators.max_pdf_size, webkarirApp.validators.pdf_valid]),
        ),
        migrations.AlterField(
            model_name='magang',
            name='email',
            field=models.CharField(max_length=100, validators=[webkarirApp.validators.email_valid]),
        ),
        migrations.AlterField(
            model_name='magang',
            name='no_hp',
            field=models.CharField(max_length=15, validators=[webkarirApp.validators.hp_numeric]),
        ),
        migrations.AlterField(
            model_name='magang',
            name='surat',
            field=models.FileField(upload_to='surat/', validators=[webkarirApp.validators.max_pdf_size, webkarirApp.validators.pdf_valid]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='no_hp',
            field=models.CharField(max_length=15, unique=True, validators=[webkarirApp.validators.hp_numeric]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='no_ktp',
            field=models.CharField(max_length=16, unique=True, validators=[webkarirApp.validators.ktp_numeric]),
        ),
    ]
